import Link from "next/link";
import { Building2, Mail, MapPin, Pencil, Phone, Plus, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  const { message } = await searchParams;
  const supabase = await createClient();
  const { data: customers, error } = await supabase.from("customers").select("*").order("last_name");
  return <><div className="mb-8 flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-950 dark:text-white">Customers</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Manage client contacts and service properties.</p></div><Link href="/customers/new" className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white hover:bg-blue-700"><Plus size={18} /> New client</Link></div>
  {message ? <div className="mb-6 rounded-xl border border-blue-200 bg-blue-50 p-4 text-blue-900">{message}</div> : null}{error ? <div className="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-900">{error.message}</div> : null}
  {!customers?.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center dark:border-slate-700 dark:bg-slate-950"><Users className="mx-auto text-slate-400" size={38} /><h2 className="mt-4 text-lg font-bold dark:text-white">No clients yet</h2><Link href="/customers/new" className="mt-4 inline-flex font-semibold text-blue-700 dark:text-blue-400">Create your first client</Link></div> : <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="hidden grid-cols-[1.4fr_1fr_1.5fr_auto] gap-4 border-b border-slate-200 bg-slate-50 px-5 py-3 text-xs font-bold uppercase text-slate-500 md:grid dark:border-slate-800 dark:bg-slate-900"><span>Client</span><span>Communication</span><span>Primary property</span><span>Options</span></div>{customers.map((c) => <article key={c.id} className="grid gap-4 border-b border-slate-100 px-5 py-5 last:border-0 md:grid-cols-[1.4fr_1fr_1.5fr_auto] md:items-center dark:border-slate-800"><div><p className="font-bold text-slate-950 dark:text-white">{c.title ? `${c.title} ` : ""}{c.first_name} {c.last_name}</p>{c.company_name ? <p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><Building2 size={14} />{c.company_name}</p> : null}</div><div className="space-y-1 text-sm text-slate-600 dark:text-slate-400">{c.phone ? <p className="flex items-center gap-2"><Phone size={15} />{c.phone}</p> : null}{c.email ? <p className="flex items-center gap-2 break-all"><Mail size={15} />{c.email}</p> : null}</div><p className="flex items-start gap-2 text-sm text-slate-600 dark:text-slate-400"><MapPin className="mt-0.5 shrink-0" size={15} /><span>{c.project_address || "No property address"}{c.city ? `, ${c.city}` : ""}{c.state ? `, ${c.state}` : ""}{c.postal_code ? ` ${c.postal_code}` : ""}</span></p><Link href={`/customers/${c.id}/edit`} className="flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-900"><Pencil size={15} /> Edit</Link></article>)}</div>}</>;
}
